name: jobs examples

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step do Job Build
        run: echo "Hello, world! Build."

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Step do Deploy
        run: echo "Hello, world! Deploy."
