name: jobs examples

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create an artifact for reuse
        run: echo "Full featured artifact" > build-result.txt

      - name: Upload the artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-result
          path: build-result.txt

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download the artifact
        uses: actions/download-artifact@v4
        with:
          name: build-result
          path: build-result.txt

      - name: Use the artifact created
        run: ls build-result.txt
