name: steps examples
on:  
  push:
    jobs:  
      hello_world_job:
        runs-on: ubuntu-latest
        name: Exemplo de ação personalizada
        steps:
          - name: Checar o código
            uses: actions/checkout@v4
          - id: step-caller
            uses: "./.github/actions/hello"
            with:
              the-caller: 'Myself'
          - name: Exibir número aleatório
            run: |
              echo "random-number: ${{ steps.step-caller.outputs.random-number }}"
            shell: bash  # Corrigido para estar no nível correto
